[release]
target_branch = "master"
branch_prefix = "release/"
tag_prefix = "v"
tag_suffix = ""
name_prefix = ""
name_suffix = ""
commit_message = "chore(release): prepare {tag}"
merge_message = "chore(release): merge {tag}"
cleanup = true
latest = true

[github]
target_repository = "verzly/tauri-release"
source_repository = "verzly/toolchain"
source_tag_prefix = "tauri-release-v"
source_tag_suffix = ""
generate_notes = true

# Distribution repositories do not contain source files or version files.
# This config is used by `github-release publish` from verzly/toolchain.
files = []
