[project]
root = "."
binary = "cargo-release"

[build]
out_dir = "dist"
default_strategy = "host"
container_engine = "podman"

[artifacts]
checksum = true
manifest = true

[targets.linux-x64]
enabled = true
triple = "x86_64-unknown-linux-gnu"
strategy = "host"
command = "cargo build --release --target x86_64-unknown-linux-gnu"
artifacts = ["target/x86_64-unknown-linux-gnu/release/cargo-release"]

[targets.windows-x64]
enabled = false
triple = "x86_64-pc-windows-msvc"
strategy = "container"
image = "ghcr.io/verzly/cargo-release-windows-msvc:latest"
command = "cargo build --release --target x86_64-pc-windows-msvc"
artifacts = ["target/x86_64-pc-windows-msvc/release/cargo-release.exe"]

[targets.macos-arm64]
enabled = false
triple = "aarch64-apple-darwin"
strategy = "host"
command = "cargo build --release --target aarch64-apple-darwin"
artifacts = ["target/aarch64-apple-darwin/release/cargo-release"]
