[release]
target_branch = "master"
branch_prefix = "release/"
tag_prefix = "toolchain-v"
tag_suffix = ""
name_prefix = "Verzly Toolchain v"
name_suffix = ""
commit_message = "chore(release): prepare {tag}"
merge_message = "chore(release): merge {tag}"
cleanup = true
latest = true

[github]
target_repository = "verzly/toolchain"
source_repository = ""
source_tag_prefix = ""
source_tag_suffix = ""
generate_notes = true

[[files]]
path = "Cargo.toml"
kind = "toml"
key = "workspace.package.version"
value = "{version}"
search = ""
replace = ""
optional = false
