[cache]
dir = ".cache"
package = "toolchain"
redirect_cargo_home = false
redirect_gradle = true

[cargo]
target_dir = "rust/packages/{package}/target"

[env]
GRADLE_USER_HOME = "android/gradle"
NPM_CONFIG_CACHE = "js/npm"
PNPM_STORE_PATH = "js/pnpm-store"
YARN_CACHE_FOLDER = "js/yarn"
