//! Gradle build output routing for Tauri Android projects.
//!
//! Gradle keeps dependency caches in `GRADLE_USER_HOME`, but project build output still defaults
//! to `<project>/build`. Tauri Android projects live under `src-tauri/gen/android`, so without an
//! init script Gradle can still leave reproducible build directories inside the repository tree.
//! This module writes a workspace-scoped Gradle init script under `.cache/android/gradle/init.d`
//! that redirects every Gradle project's `buildDirectory` into `.cache/android/builds`.

use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

const INIT_SCRIPT_NAME: &str = "verzly-build-cache.gradle";

pub fn init_script_path(gradle_user_home: &Path) -> PathBuf {
    gradle_user_home.join("init.d").join(INIT_SCRIPT_NAME)
}

pub fn write_init_script(
    script_path: &Path,
    workspace_root: &Path,
    build_root: &Path,
) -> Result<()> {
    if let Some(parent) = script_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }

    fs::create_dir_all(build_root)
        .with_context(|| format!("failed to create {}", build_root.display()))?;

    fs::write(script_path, render_init_script(workspace_root, build_root))
        .with_context(|| format!("failed to write {}", script_path.display()))?;

    Ok(())
}

fn render_init_script(workspace_root: &Path, build_root: &Path) -> String {
    format!(
        r#"// Generated by verzly rust-cache. Do not edit by hand.
// Routes Gradle/Tauri Android project build directories into the repository cache root.

import java.security.MessageDigest

ext.verzlyWorkspaceRoot = new File('{workspace_root}').canonicalFile.toPath()
ext.verzlyGradleBuildRoot = new File('{build_root}').canonicalFile

ext.verzlyCacheHash = {{ String value ->
    MessageDigest
        .getInstance('SHA-256')
        .digest(value.getBytes('UTF-8'))
        .encodeHex()
        .toString()
        .substring(0, 16)
}}

allprojects {{ project ->
    def projectPath = project.projectDir.canonicalFile.toPath()

    if (projectPath.startsWith(verzlyWorkspaceRoot)) {{
        def relativePath = verzlyWorkspaceRoot.relativize(projectPath).toString()
        if (relativePath == null || relativePath.trim().isEmpty()) {{
            relativePath = 'root'
        }}

        relativePath = relativePath
            .replace(File.separator, '_')
            .replaceAll('[^A-Za-z0-9._-]', '_')

        def bucket = relativePath + '-' + verzlyCacheHash(projectPath.toString())
        def outputDir = new File(verzlyGradleBuildRoot, bucket)

        try {{
            project.layout.buildDirectory.set(outputDir)
        }} catch (Throwable ignored) {{
            project.buildDir = outputDir
        }}
    }}
}}
"#,
        workspace_root = groovy_path(workspace_root),
        build_root = groovy_path(build_root),
    )
}

fn groovy_path(path: &Path) -> String {
    path.display()
        .to_string()
        .replace('\\', "\\\\")
        .replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_dir(name: &str) -> PathBuf {
        let suffix = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock")
            .as_nanos();
        let path = std::env::temp_dir().join(format!("rust-cache-gradle-{name}-{suffix}"));
        fs::create_dir_all(&path).expect("create temp dir");
        path
    }

    #[test]
    fn writes_workspace_scoped_gradle_init_script() {
        let root = temp_dir("write");
        let script = root.join(".cache/android/gradle/init.d/verzly-build-cache.gradle");
        let build_root = root.join(".cache/android/builds");

        write_init_script(&script, &root, &build_root).expect("write init script");

        let content = fs::read_to_string(script).expect("read script");
        assert!(content.contains("allprojects"));
        assert!(content.contains("buildDirectory"));
        assert!(content.contains("verzlyGradleBuildRoot"));
        assert!(build_root.exists());
    }

    #[test]
    fn escapes_paths_for_groovy_single_quoted_strings() {
        assert_eq!(
            groovy_path(Path::new("C:\\work\\it's")),
            "C:\\\\work\\\\it\\'s"
        );
    }
}
